config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create' , via: :get
  match 'auth/failure', to: redirect('/'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get
  get 'find/search'
  get 'find/show'
  get 'find/detail'
  get 'find/advanced'
  get 'find/corrupt'
  get 'find/ads'
  get 'find/nearest'
  get 'find/nearestresult'
  get 'agents/waited'

  devise_for :users #, :controllers => {:registerations=> "registerations"}
  resources :agents do
       member do
         get 'toggle'
         get 'mapandroute'
         
    end
  end

  resources :activities

  resources :neighbours

  resources :regions
  get 'domiat/cleanall'
  get 'domiat/art'
  get 'domiat/users'
  get 'domiat/user/:id' => 'domiat#user'

  get 'domiat/clean'
  get 'domiat/exception'
  get 'domiat/show/:id'  => 'domiat#show'
  get 'domiat/welcome'
  match 'about' => 'domiat#about', :as => 'about', via: :get
  root 'domiat#welcome'
  resources :posts
  get 'suggest' => 'posts#suggest'
  get 'wantdelete' => 'posts#wantdelete'
  get 'newactivity' => 'posts#newactivity'
  get 'wrongdata' => 'posts#wrongdata'
  get 'complain' => 'posts#complain'

end

app/controllers/find_controller.rb
# encoding: UTF-8
class FindController < ApplicationController
    before_action :set_verified_agent, only: [:show_map, :show_route]
    before_action :set_verified_agent #, :corrupt 
    before_action :test_if_more_than_one  , only: [ :advanced ]
 
  def search
    @clean_params=(params[:search]).gsub(/\s+/, ' ')
    query="%" + @clean_params + "%"
    @auto=[]
    @auto.concat(@verified_agent.where('name LIKE ?', query).limit(5).pluck(:name))
    @auto.concat(@verified_agent.where('activity LIKE ?', query).limit(5).pluck(:activity))
    @auto.concat(@verified_agent.where('word1 LIKE ?', query).limit(5).pluck(:word1))
    @auto.concat(@verified_agent.where('word2 LIKE ?', query).limit(5).pluck(:word2))
    @auto.concat(@verified_agent.where('word3 LIKE ?', query).limit(5).pluck(:word3))
    @auto.concat(@verified_agent.where('word4 LIKE ?', query).limit(5).pluck(:word4))
    @auto.concat(@verified_agent.where('word5 LIKE ?', query).limit(5).pluck(:word5))
    @auto.uniq!
  end

  def corrupt
    if params[:search] and (((params[:search]).gsub(/\s+/, '')).length>0)
    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
    @encrypted_data = crypt.encrypt_and_sign(params[:search])
    else
            redirect_to :root
    end
  end

  def show
    if params[:search] and (((params[:search]).gsub(/\s+/, '')).length>0)
    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
    @clean_params = crypt.decrypt_and_verify(params[:search])
    @result=@verified_agent.where('name=? OR activity=? OR word1=? OR word2=? OR word3=? OR word4=? OR word5=?',@clean_params,@clean_params,@clean_params,@clean_params,@clean_params,@clean_params,@clean_params).page params[:page]
        respond_to do |format|
            format.html 
            format.js 
        end
      else
        redirect_to :root
    end
  end

   def detail
    @result=@verified_agent.select(:id,:name,:activity,:brief_of_activity).limit(5).order("RANDOM()")
   #   redirect_to :controller=>'find', :action=>'show', :search => params[:search]
    end

  def advanced
    @result=[]
    where_first_clause=""
    where_second_clause=""
    has_previous=false
      params.each do |key,value|
        if key.in?(['name','region','neighbour','street','activity'])
          if  !value.blank?
              if has_previous
                where_first_clause << "AND #{key} LIKE ? "
                where_second_clause << ","+"%" + value + "%"
              else
                where_first_clause << " #{key} LIKE ? "
                where_second_clause << "%" + value + "%"
                has_previous=true
              end #for if
          end # for if
        end #for if
        end #for do
        puts where_first_clause
        puts where_second_clause
        
        key='twenty_four'
        if params[:twenty_four]
              if has_previous
                where_first_clause << "AND #{key}= ? "
                where_second_clause << "," + "true" 
              else
                where_first_clause << " #{key} = ? "
                where_second_clause <<  "true" 
                has_previous=true
              end
        # else
        #       if has_previous
        #         where_first_clause << "AND #{key}= ? "
        #         where_second_clause << "," + "false" 
        #       else
        #         where_first_clause << " #{key} = ? "
        #         where_second_clause <<  "false" 
        #         has_previous=true
        #       end
        end # if params
            values= where_second_clause.split(',')
            length_of_array=values.length
            case length_of_array
            when 1
              @result= @verified_agent.where(where_first_clause,values[0]).page params[:page]
            when 2
              @result= @verified_agent.where(where_first_clause,values[0],values[1]).page params[:page]
            when 3
              @result= @verified_agent.where(where_first_clause,values[0],values[1],values[2]).page params[:page]
            when 4
              @result= @verified_agent.where(where_first_clause,values[0],values[1],values[2],values[3]).page params[:page]
            when 5
              @result= @verified_agent.where(where_first_clause,values[0],values[1],values[2],values[3],values[4]).page params[:page]
            when 6
              @result= @verified_agent.where(where_first_clause,values[0],values[1],values[2],values[3],values[4],values[5]).page params[:page]
            when 7
              @result= @verified_agent.where(where_first_clause,values[0],values[1],values[2],values[3],values[4],values[5],values[6]).page params[:page]
            end # of case 
          
    if !params[:word].blank?
    @result=@result.where('word1=? OR word2=? OR word3=? OR word4=? OR word5=?',params[:word],params[:word],params[:word],params[:word],params[:word]).page params[:page]
    end

    @result.uniq!
  end # end of advanced

  def ads
      sent_activity=params[:activity]
      @result=@verified_agent.select(:id, :name,:activity,:brief_of_activity).where('activity=? ',sent_activity).limit(5).order("RANDOM()")
  end

  def nearest
  end

  def nearestresult
    sent_activity=params[:activity]
     x= params[:latitude].to_f
    y=params[:langitude].to_f
    id=@verified_agent.select(:id).where('activity=? ',sent_activity).by_distance(:origin => [x,y]).first
    if id.present?
        redirect_to agent_path(id)
    else
        flash[:error] = "عفواً لا يوجد نشاط  #{sent_activity} متاح اﻵن."
        redirect_to :find_detail
    end
  end

  private
  
  def set_verified_agent
        @verified_agent=Agent.where('ok=?',true)
  end

  def test_if_more_than_one
     n=0
    params.each do |key,value|
        if key.in?(['name','region','neighbour','street','activity','word'])
            if !value.blank?
              puts key
              puts value
              n=n+1
            end
        end
    end

    if params.length==11
      n=n+1
    end

    if n<2
       flash[:error] = "يجب إختيار اثنين أو أكثر من تفاصيل البحث."
        redirect_to :find_detail
    end

  end # of test_if_more_than_one

end

app/helpers/find_helper.rb
module FindHelper
end

app/views/find/_data.html.erb
<% unless @result.blank? %>
	<h3>نتائج البحث</h3>

	<table class="table table-hover" border="2">
  <thead>
    <tr>
      <th>الاسم</th>
      <th>الحي أو المنطقة</th>
      <th>المجاورة</th>
      <th>النشاط</th>
      <th>أيام العطلة</th>
      <th>24 ساعة</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th>بداية العمل</th>
      <th>نهاية العمل</th>
    </tr>
  </thead>

  <tbody>
    <% @result.each do |agent| %>
      <tr>
        <td><%= link_to truncate(agent.name, :length => 20), agent %></td>
        <td><%= truncate(agent.region, :length => 20) %></td>
        <td><%= truncate(agent.neighbour, :length => 20) %></td>
        <td><%= truncate(agent.activity, :length => 20) %></td>
        <td><%= agent.day_off.drop(1) %></td>
        <td>
          <% if agent.twenty_four %>
          <strong>نعم</strong>
          <% else %>
          <strong>لا</strong>
          <% end %>
        </td>
        <td><%= truncate(agent.tel1, :length => 15) %></td>
        <td><%= truncate(agent.tel2, :length => 15) %></td>
        <td><%= truncate(agent.tel3, :length => 15) %></td>
        <td><%= (agent.start).strftime("%I:%M %P") %></td>
        <td><%= (agent.end).strftime("%I:%M %P") %></td>
                        
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/find/ads.html.erb
<h1>Hello from ads.html.erb</h1>

app/views/find/ads.js.erb
// $("div.alert").fadeOut(500);
$("div.alert").removeClass("now");
var income_results="<%= raw @result.length %>"
if ( income_results != 0) {
	var counter=0
	<% @result.each do |result| %> 
		 // $("div.alert:eq("+counter+")").css("height","90px");
		 $("div.alert>b>a:eq(" + counter + ")").replaceWith("<%= j link_to result.name, result %>");
		 $("div.alert>i:eq(" + counter + ")").text("<%= raw result.brief_of_activity %>");
		 $("div.alert>code:eq(" + counter + ")").text("<%= raw result.activity %>");
		 $("div.alert:eq(" + counter + ")").addClass("now");
			counter+=1
	<% end %>

		 $("div.alert>code:eq(0)").trigger("change");
	// for(k=counter; k<=5;k++){
	// 	  // $("div.alert:eq("+k+")").css("height","0px");
	// 	  $("div.alert:eq("+k+")").fadeOut(500);


	// }
} //if

app/views/find/advanced.html.erb
<% unless @result.blank? %>
	<h3>نتائج البحث</h3>

	<table class="table table-hover table-striped" border="2">
  <thead>
    <tr>
      <th>الاسم</th>
      <th>النشاط</th>
      <th class='hide_in_tablet hide_in_phone'>الحي أو المنطقة</th>
      <th class='hide_in_tablet hide_in_phone'>المجاورة</th>
      <th>أيام العطلة</th>
      <th class='hide_in_phone'>24 ساعة</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th class='hide_in_phone'>تليفون</th>
      <th class='hide_in_tablet hide_in_phone'>بداية العمل</th>
      <th class='hide_in_tablet hide_in_phone'>نهاية العمل</th>
    </tr>
  </thead>

  <tbody>
    <% @result.each do |agent| %>
      <tr>
        <td><%= link_to truncate(agent.name, :length => 20), agent %></td>
        <td><%= truncate(agent.activity, :length => 20) %></td>
        <td class='hide_in_tablet hide_in_phone'><%= truncate(agent.region, :length => 20) %></td>
        <td class='hide_in_tablet hide_in_phone'><%= truncate(agent.neighbour, :length => 20) %></td>
        
        <td><%= agent.day_off.drop(1) %></td>
        <td class='hide_in_phone'>
          <% if agent.twenty_four %>
          <strong>نعم</strong>
          <% else %>
          <strong>لا</strong>
          <% end %>
        </td>
        <td><%= truncate(agent.tel1, :length => 15) %></td>
        <td><%= truncate(agent.tel2, :length => 15) %></td>
        <td class='hide_in_phone'><%= truncate(agent.tel3, :length => 15) %></td>
        <td class='hide_in_tablet hide_in_phone'><%= (agent.start).strftime("%I:%M %P") %></td>
        <td class='hide_in_tablet hide_in_phone'><%= (agent.end).strftime("%I:%M %P") %></td>
                        
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h3>عفواً لا يوجد نتائج لهذا البحث.</h3>
<% end %>
<%= paginate @result %>
<%= link_to 'عودة', url_for(:back), :class => "btn btn-primary" %>

app/views/find/corrupt.js.erb
var target='<%= raw @encrypted_data %>'
window.location.replace("/find/show?search="+ target);

app/views/find/detail.html.erb
<div class="container">
    <div class="row" >
  <h2>البحث عن أقرب نشاط : </h2>
<div id='demo'></div>

<%= form_tag find_nearestresult_path, method:"get" do  %>
  
     <div class="col-md-6"  id="make_it_right">

<div class="form-group" data-no-turbolink>
    <%= collection_select("", :activity, Activity.all, :name, :name, {:prompt => "اختر النشاط"},{:multiple =>false, :class => "form-control", :style => "width:250px;"})  %>
</div>

    <%= hidden_field_tag :latitude ,'', :style =>"width:250px;",:id=>"latitude" %>

   <%= hidden_field_tag :langitude ,'', :style =>"width:250px;",:id=>"langitude" %>

<div class="form-group">
        <div class="actions">
        
          <%= submit_tag "بحث", :class => "btn btn-success btn-lg  active_after_activity", :id=>"nearest_search", disabled:true %>
        </div>
</div>
<% end %>
</div>
</div>
<hr>
<div class="container">
    <div class="row">
<%= form_tag find_advanced_path, method:"get" do  %>
  <h2>بحث مفصَّل:</h2>

     <div class="col-md-6" id="make_it_right" >

      <div class="form-group">
        <%= label_tag "فئة النشاط" %><br><%= collection_select("", :activity, Activity.all, :name, :name, {:prompt => "اختر النشاط"},{:multiple =>false,:class => "form-control ", :id=>"activity_select" , :style =>"width:250px;"})  %>
      </div>
     	<div class="form-group">
        <%= label_tag "اسم النشاط" %><%= text_field_tag :name ,'',:class =>"form-control active_after_activity", :style =>"width:250px;", disabled:true %>
        </div>
        <div class="form-group">
        <%= label_tag "الحي او المنطقة" %><br><%= collection_select("", :region, Region.all, :name, :name, {:prompt => "اختر الحي أو المنطقة"},{:multiple =>false,:id=> 'agent_region',:class => "form-control active_after_activity", :style =>"width:250px;", disabled:true}) %>
        </div>
        <div class="form-group">
        <%= label_tag "المجاورة أو الناحية" %><br><%= collection_select("", :neighbour, Neighbour.all, :name, :name, {:prompt => "اختر المجاورة أو الناحية"},{:multiple =>false,:id=> 'agent_neighbour',:class => "form-control active_after_activity" , :style =>"width:250px;", disabled:true}) %>
        </div>
        
     </div>

     <div class="col-md-6" >
     	
      <div class="form-group">
        <%= label_tag "الشارع" %><%= text_field_tag :street ,'',:class =>"form-control active_after_activity", :style =>"width:250px;", disabled:true %>
        </div>

        <div class="form-group"> 
        <%= label_tag "كلمة بحث" %><%= text_field_tag :word ,'',:class =>"form-control active_after_activity", :style =>"width:250px;" , disabled:true %>
      </div> 
        <div class="form-group" >
          <%= label_tag "العمل 24 ساعة يومياً" %>
         
 			<%= check_box_tag :twenty_four , "", checked = false, {:class => "form-control active_after_activity",:style=>"width:30px;", disabled:true} %>
        </div> 
        <div class="form-group">
        <div class="actions">
        
          <%= submit_tag "بحث", :class => "btn btn-success btn-lg  active_after_activity", disabled:true %>
        </div>
        </div>
     </div>
     </div>

<% end %>
     </div>
     </div>
    <div id="side_ads" style="  position: absolute;
  width: 21%;
  background-color:rgb(32,0,0) ;
  top: 57px;
  left: 5px;">
<p style="margin-top: 10px;
  margin-bottom: 0; font-size:16px; text-align:center; color:goldenrod;">أنشطة مقترحة عشوائياً</p><br>
<% div_colors=["alert-primary","alert-success","alert-info","alert-warning","alert-danger"] %>

<% i=0 %>
<% @result.each do |result| %>
<div class="alert <%= div_colors[i] %>" role="alert" >
  <b><%= link_to result.name, result %></b>
  <br>
  <code><%= result.activity %></code>
  <br>
  <i><%= result.brief_of_activity %>.</i>
</div>
<% i=i+1 %>
<% end %>
</div>

</div>

<script type="text/javascript">
$(document).ready(function(){
  getLocation();
});
var x = document.getElementById("demo");
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "<p>يجب عليك تمكين الكشف عن موقعك للإستمرار</p>";
    }
}
function showPosition(position) {
  // alert("hello");
    $('#latitude').val(position.coords.latitude)  ;

    $('#langitude').val(position.coords.longitude);
}
</script>

app/views/find/nearest.html.erb
<p style="font-size:20px;">البحث عن أقرب نشاط : </p>
<div id='demo'></div>
<%= form_tag find_nearestresult_path, method:"get" do  %>

<div class="form-group" data-no-turbolink>
		<%= collection_select("", :activity, Activity.all, :name, :name, {:prompt => "اختر النشاط"},{:multiple =>false, :class => "form-control", :style => "width:250px;"})  %>
</div>


    <%= hidden_field_tag :latitude ,'', :style =>"width:250px;",:id=>"latitude" %>



   <%= hidden_field_tag :langitude ,'', :style =>"width:250px;",:id=>"langitude" %>



<div class="form-group">
        <div class="actions">
        
          <%= submit_tag "بحث", :class => "btn btn-success btn-lg  active_after_activity", :id=>"nearest_search", disabled:true %>
        </div>
</div>
<% end %>

<script type="text/javascript">
$(document).ready(function(){
	getLocation();
});
var x = document.getElementById("demo");
function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "<p>يجب عليك تمكين الكشف عن موقعك للإستمرار</p>";
    }
}
function showPosition(position) {
	// alert("hello");
    $('#latitude').val(position.coords.latitude)  ;

    $('#langitude').val(position.coords.longitude);
}
</script>

app/views/find/nearestresult.html.erb
<h4>List of nearest activities.</h4>

app/views/find/search.html.erb
<% unless @auto.blank? %>
	<h3>نتائج البحث</h3>

	<table class="table table-hover" border="2">
  <thead>
    <tr>
      <th>الاسم</th>
      <th>الحي أو المنطقة</th>
      <th>المجاورة</th>
      <th>النشاط</th>
      <th>أيام العطلة</th>
      <th>24 ساعة</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th>بداية العمل</th>
      <th>نهاية العمل</th>
    </tr>
  </thead>

  <tbody>
    <% @auto.each do |agent| %>
      <tr>
        <td><%= link_to truncate(agent.name, :length => 20), agent %></td>
        <td><%= truncate(agent.region, :length => 20) %></td>
        <td><%= truncate(agent.neighbour, :length => 20) %></td>
        <td><%= truncate(agent.activity, :length => 20) %></td>
        <td><%= agent.day_off.drop(1) %></td>
        <td>
          <% if agent.twenty_four %>
          <strong>نعم</strong>
          <% else %>
          <strong>لا</strong>
          <% end %>
        </td>
        <td><%= truncate(agent.tel1, :length => 15) %></td>
        <td><%= truncate(agent.tel2, :length => 15) %></td>
        <td><%= truncate(agent.tel3, :length => 15) %></td>
        <td><%= (agent.start).strftime("%I:%M %P") %></td>
        <td><%= (agent.end).strftime("%I:%M %P") %></td>
                        
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/find/search.js.erb
$(function() {

    var availableTags = <%= raw @auto %> ;
    $( "#search" ).autocomplete({
      source: availableTags
    });
    // $("#corruption").text("<%= raw @encrypted_data %>")
  });

app/views/find/show.html.erb
<% unless @result.blank? %>
	<h3>نتائج البحث</h3>

	<table class="table table-hover table-striped" border="2">
  <thead>
    <tr>
      <th>الاسم</th>
      <th>الخريطة و المسار</th>
      <th>النشاط</th>
      <th class='hide_in_tablet hide_in_phone'>الحي أو المنطقة</th>
      <th class='hide_in_tablet hide_in_phone'>المجاورة</th>
      <th>أيام العطلة</th>
      <th class='hide_in_phone'>24 ساعة</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th class='hide_in_phone'>تليفون</th>
      <th class='hide_in_tablet hide_in_phone'>بداية العمل</th>
      <th class='hide_in_tablet hide_in_phone'>نهاية العمل</th>
    </tr>
  </thead>

  <tbody>
    <% @result.each do |agent| %>
      <tr>
        <td><%= link_to truncate(agent.name, :length => 25), agent %></td>

        <td style="text-align:center;" data-no-turbolink >
       
      <% unless (agent.latitude.blank? or agent.langitude.blank?) %>
            <% if current_user.try(:admin?)  %>
                      <%= link_to "الخريطة و المسار", mapandroute_agent_path(agent), :class => "btn btn-success", :style => "width:100%;" %>
            <% elsif agent.ok %>
                      <%= link_to "الخريطة و المسار", mapandroute_agent_path(agent), :class => "btn btn-success", :style => "width:100%;" %>
                 
            <% end %>
            
      <% else %>
               <strong>هذا النشاط لم يتم تسجيب احداثياتة حتى اﻵن.</strong>

      <% end %>
    </td>
        
        <td><%= truncate(agent.activity, :length => 20) %></td>
        <td class='hide_in_tablet hide_in_phone'><%= truncate(agent.region, :length => 20) %></td>
        <td class='hide_in_tablet hide_in_phone'><%= truncate(agent.neighbour, :length => 20) %></td>
        
        <td><%= agent.day_off.drop(1) %></td>
        <td class='hide_in_phone'>
          <% if agent.twenty_four %>
          <strong>نعم</strong>
          <% else %>
          <strong>لا</strong>
          <% end %>
        </td>
        <td><%= truncate(agent.tel1, :length => 15) %></td>
        <td><%= truncate(agent.tel2, :length => 15) %></td>
        <td class='hide_in_phone'><%= truncate(agent.tel3, :length => 15) %></td>
        <td class='hide_in_tablet hide_in_phone'><%= (agent.start).strftime("%I:%M %P") %></td>
        <td class='hide_in_tablet hide_in_phone'><%= (agent.end).strftime("%I:%M %P") %></td>
                        
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>
<%= paginate @result %>

<%= link_to 'عودة', url_for(:back), :class => "btn btn-primary", :style => "width:200px;" %>

app/views/find/show.js.erb
// //alert("Hello from show.js.erb");
// $("#result").html("<%=j render 'data' %>");
// var url = "/find/testing";    
// $(location).attr('href',url);
var target='<%= raw @encrypted_data %>'
window.location.replace("/find/show?search="+ target);