config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create' , via: :get
  match 'auth/failure', to: redirect('/'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get
  get 'find/search'
  get 'find/show'
  get 'find/detail'
  get 'find/advanced'
  get 'find/corrupt'
  get 'find/ads'
  get 'find/nearest'
  get 'find/nearestresult'
  get 'agents/waited'

  devise_for :users #, :controllers => {:registerations=> "registerations"}
  resources :agents do
       member do
         get 'toggle'
         get 'mapandroute'
         
    end
  end

  resources :activities

  resources :neighbours

  resources :regions
  get 'domiat/cleanall'
  get 'domiat/art'
  get 'domiat/users'
  get 'domiat/user/:id' => 'domiat#user'

  get 'domiat/clean'
  get 'domiat/exception'
  get 'domiat/show/:id'  => 'domiat#show'
  get 'domiat/welcome'
  match 'about' => 'domiat#about', :as => 'about', via: :get
  root 'domiat#welcome'
  resources :posts
  get 'suggest' => 'posts#suggest'
  get 'wantdelete' => 'posts#wantdelete'
  get 'newactivity' => 'posts#newactivity'
  get 'wrongdata' => 'posts#wrongdata'
  get 'complain' => 'posts#complain'

end

app/models/agent.rb
# encoding: UTF-8
class Agent < ActiveRecord::Base
	#before_save {self.email=email.downcase}
acts_as_mappable :default_units => :kms,
               :default_formula => :flat,
               :distance_field_name => :distance,
               :lat_column_name => :latitude,
               :lng_column_name => :langitude

validates :name , :presence => { message:"اسم النشاط يجب أن يكون موجوداً"}, 
					length:{maximum:25, message:"اسم النشاط لا يزيد عن 25 حروف"} ,
					 length:{minimum:6, message:"اسم النشاط لا يقل عن 6 حروف"}

validates :activity , :presence => { message:" النشاط يجب أن يكون موجوداً"}, 
					length:{maximum:15, message:"النشاط لا يزيد عن 15 حروف"} ,
					 length:{minimum:4, message:"النشاط لا يقل عن 4 حروف"}

validates :brief_of_activity , :presence => { message:"مختصر النشاط يجب أن يكون موجوداً"}, 
					length:{maximum:100, message:"مختصر النشاط لا يزيد عن 100 حروف"} ,
					 length:{minimum:20, message:"مختصر النشاط لا يقل عن 20 حروف"}

validates :street , :presence => { message:"اسم الشارع يجب أن يكون موجوداً"}, 
					length:{maximum:15, message:"اسم الشارع لا يزيد عن 15 حروف"} ,
					 length:{minimum:5, message:"اسم الشارع لا يقل عن 5 حروف"}

validates :address , :presence => { message:"العنوان يجب أن يكون موجوداً"}, 
					length:{maximum:25, message:"العنوان لا يزيد عن 25 حروف"} ,
					 length:{minimum:10, message:"العنوان لا يقل عن 10 حروف"}

validates :region , :presence => { message:"اسم المنطقة أو الحي يجب أن يكون موجوداً"}, 
					length:{maximum:15, message:"اسم المنطقة أو الحي لا يزيد عن 15 حروف"} ,
					 length:{minimum:5, message:"اسم المنطقة أو الحي لا يقل عن 5 حروف"}

validates :neighbour , :presence => { message:"اسم المجاورة أو الناحية يجب أن يكون موجوداً"}, 
					length:{maximum:15, message:"اسم المجاورة أو الناحية لا يزيد عن 15 حروف"} ,
					 length:{minimum:5, message:"اسم المجاورة أو الناحية لا يقل عن 5 حروف"}

validates :tel1 , :presence => { message:"رقم التليفون اﻷول يجب أن يكون موجوداً"}, 
					length:{is:11, message:"رقم التليفون اﻷول يجب أن يكون مكون من 11 رقما و يجب ان يكون موبايل"} ,
					 # length:{minimum:11, message:"رقم التليفون اﻷول لا يقل عن 11 رقما و يجب ان يكون موبايل"},
					 :uniqueness => { message:"رقم التليفون الذي أدخلته موجود مسبقاً"}

validates :latitude , :presence => { message:"الاحداثي يجب أن يكون موجوداً"}, 
					length:{maximum:18, message:"الاحداثي لا يزيد عن 18 رقم"} ,
					 length:{minimum:8, message:"الاحداثي لا يقل عن 8 أرقام"}

validates :langitude ,  :presence => { message:"الاحداثي يجب أن يكون موجوداً"}, 
					length:{maximum:18, message:"الاحداثي لا يزيد عن 18 رقم"} ,
					 length:{minimum:8, message:"الاحداثي لا يقل عن 8 أرقام"}

validates :tel1, numericality: { only_integer: true, message:"رقم التليفون يجب أن يكون أرقام فقط." }

  validates_numericality_of :latitude, greater_than_or_equal_to:31.4010, less_than_or_equal_to: 31.4635, message:"هذا اﻹحداثي خارج دمياط الجديدة و توابعها"

  validates_numericality_of :langitude, greater_than_or_equal_to: 31.6367, less_than_or_equal_to: 31.72, message:"هذا اﻹحداثي خارج دمياط الجديدة و توابعها"

  validates :tel2,:tel3, numericality: { only_integer: true, :allow_blank => true, :message =>"رقم التليفون يجب أن يكون أرقام فقط. أو فارغاً" } ,
  			:uniqueness => { message:"رقم التليفون الذي أدخلته موجود مسبقاً"}
 validate :start_equal_end_time

  	def start_equal_end_time
		if self.start == self.end
			errors.add(:end, 'لا يمكن أن يكون وقت بداية العمل يساوي وقت اﻹنتهاء طالما أنك لم تعمل 24 ساعة') unless self.twenty_four
		end
  	end

	belongs_to :user
  apply_simple_captcha

  DAYS = [ "الجمعة", "اﻷحد", "الإثنين", "الثلاثاء", "اﻷربعاء", "الخميس", "السبت" ]

 end

app/controllers/agents_controller.rb
# encoding: UTF-8
class AgentsController < ApplicationController
      include AgentsHelper
      include SimpleCaptcha::ControllerHelpers
  before_filter :authenticate_user!, except: [:show, :mapandroute ]
     #the arrange or the dependency of i_am_admin_or_owner on set_agent is important.
  before_action :set_agent, only: [ :i_am_admin_or_owner, :toggle, :show, :edit, :update, :destroy]
  before_action :set_verified_agent, only: [:mapandroute]
  before_action :i_am_admin_or_owner , only: [ :edit, :update, :destroy]

  # GET /agents
  # GET /agents.json
  def index
    if current_user.try(:admin?) 
    @agents = Agent.all.order(:name)
    else
      redirect_to :root 
    end
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
      # AWS.config(access_key_id:     ENV['S3_ACCESS_KEY_ID'],
      #            secret_access_key: ENV['S3_SECRET_ACCESS_KEY'] )

      # S3_BUCKET = AWS::S3.new.buckets[ENV'S3_BUCKET']
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  def waited
    
    if current_user.is_admin? 
    @agents = Agent.where(:ok => false).order(:created_at)
    else
      redirect_to :root 
    end
  end
  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  # POST /agents.json
  def create
    #render :text => params.inspect
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if  (@agent.save_with_captcha and @agent.update(:user_id => current_user.id))
        # AgentMailer.welcome_email(@agent).deliver_now
        #sending SMS with saved agent's data
        # send_sms(@agent)
        # AgentMailer.inform_admin(@agent).deliver_now

        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if (@agent.update(agent_params) and @agent.update(:ok => false))
        format.html { redirect_to @agent, notice: 'تم التعديل بنجاح و ستم انتظار المراجة في أقرب وقت ممكن.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #verify action is to mark the "ok" field in the agents table to true to be showon in searching.
  # verify is a member of agents route- get agents/:id/verify.
  def toggle

    if current_user.is_admin? 
          if @agent.ok 
               @agent.update_attribute(:ok,false)
               flash[:notice] = "The agent is waited"
          else
              @agent.update_attribute(:ok,true)
              flash[:notice] = "The agent is verified, ThanX  "
          end
        redirect_to :agents_waited
    end
  end

  def mapandroute
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    def set_verified_agent
      if current_user
            if current_user.is_admin?

              @agent = Agent.find(params[:id])
            else
            @agent= Agent.where(:ok => true).find(params[:id])
            end
      else
           @agent= Agent.where(:ok => true).find(params[:id])

      end
    end
# verify if the current user is admin , if not, redirect_to the root path
    def i_am_admin_or_owner
      unless ((current_user.is_admin?) or (@agent.email==current_user.email))
        redirect_to :root    
        flash[:error] = "ليس لديك الحق في رؤية هذة الصفحة."
     
       end
    end
    def i_am_admin
      current_user.is_admin?

    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      params[:agent][:day_off] ||= []
      params.require(:agent).permit(:name, :region, :neighbour, :street, :address, :activity, :brief_of_activity, :twenty_four, :word1, :word2, :word3, :word4, :word5, :tel1, :tel2, :tel3, :email, :start, :end, :website1, :website2, :can_announce, :captcha, :captcha_key, :latitude, :langitude, day_off: [])
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
 def send_sms(agent)
  		accountSID = 'AC399f914ac8260eff456fa5da65da9f5b'
        authToken ='370952cfd2245b1cd8c658dd049d70af'
        client = Twilio::REST::Client.new accountSID, authToken
        from = '+12138175357'
        #@admins.each do |admin|
        friends = {'+201000200697'=> "#{agent.name}"}
        friends.each do |key, value|
           client.account.messages.create(
             :from => from,
             :to => key,
             :body => "#{@agent.name} has signed up, with number #{agent.tel1}") 
          puts "Sent message to #{agent.name} with number #{agent.tel1}"
        end
 end
end

app/views/agents/edit.html.erb
<h1>Editing Agent</h1>

<%= render 'form' %>

<%= link_to 'Show', @agent %> |
<%= link_to 'Back', agents_path %>

app/views/agents/index.html.erb
<h1>Listing Agents</h1>

<table class="table table-hover table-striped" border="2"  data-no-turbolink >
  <thead>
    <tr>
      <th>الاسم</th>
      <th>الحي أو المنطقة</th>
      <th>المجاورة</th>
      <th>الشارع</th>
      <th>العنوان</th>
      <th>النشاط</th>
      <th>مختصر عن النشاط</th>
      <th>أيام العطلة</th>
      <th>24 ساعة</th>
      <th>كلمة بحث</th>
      <th>كلمة بحث</th>
      <th>كلمة بحث</th>
      <th>كلمة بحث</th>
      <th>كلمة بحث</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th>بريد الكتروني</th>
      <th>بداية العمل</th>
      <th>نهاية العمل</th>
      <th>موقع نت</th>
      <th>موقع نت</th>
      <th>الإعلان</th>
      <th>Map</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= link_to truncate(agent.name, :length => 20), agent %></td>
        <td><%= truncate(agent.region, :length => 20) %></td>
        <td><%= truncate(agent.neighbour, :length => 20) %></td>
        <td><%= truncate(agent.street, :length => 20) %></td>
        <td title='<%= agent.address %>'><%= truncate(agent.address, :length => 20)  %></td>
        <td><%= truncate(agent.activity, :length => 20) %></td>
        <td title='<%= agent.brief_of_activity %>' ><%= truncate(agent.brief_of_activity, :length => 20) %></td>
        <td><%= agent.day_off.drop(1) %></td>
        <td>
          <% if agent.twenty_four %>
          <strong>نعم</strong>
          <% else %>
          <strong>لا</strong>
          <% end %>
        </td>
        <td><%= truncate(agent.word1, :length => 10) %></td>
        <td><%= truncate(agent.word2, :length => 10) %></td>
        <td><%= truncate(agent.word3, :length => 10) %></td>
        <td><%= truncate(agent.word4, :length => 10) %></td>
        <td><%= truncate(agent.word5, :length => 10) %></td>
        <td><%= truncate(agent.tel1, :length => 15) %></td>
        <td><%= truncate(agent.tel2, :length => 15) %></td>
        <td><%= truncate(agent.tel3, :length => 15) %></td>
        <td title='<%= agent.email %>'><%= truncate(agent.email, :length => 20) %></td>
        <td><%= (agent.start).strftime("%I:%M %P") %></td>
        <td><%= (agent.end).strftime("%I:%M %P") %></td>
        <td title='<%= agent.website1 %>'><%= truncate(agent.website1, :length => 20) %></td>
        <td title='<%= agent.website2 %>'><%= truncate(agent.website2, :length => 20) %></td>
        <td>
          <% if agent.can_announce %>
          <strong>نعم</strong>
          <% else %>
          <strong>لا</strong>
          <% end %>
        </td>
        <td style="text-align:center;"><%= link_to "الخريطة", mapandroute_agent_path(agent), :class => "btn btn-success" %>
        </td>
        
        <td><%= link_to 'تعديل', edit_agent_path(agent), :class => "btn btn-primary" %></td>

        <td>
              <% if agent.ok  %>
            <%= link_to 'تعليق', toggle_agent_path(agent), :class => "btn btn-info" %>
            <% else %>
            <%= link_to 'اقرار', toggle_agent_path(agent), :class => "btn btn-success" %>
            <% end %>
        </td>
            
        <td><%= link_to 'حذف', agent,:class => "btn btn-danger", method: :delete, data: { confirm: 'هل أنت متأكد من رغبتك في الحذف?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agent', new_agent_path, :class => "btn btn-success" %>

app/views/agents/new.html.erb
<h1>نشاط جديد</h1>
<hr>
<%= render 'form' %>

<%= link_to 'عودة', agents_path, :class => "btn btn-primary" %>

app/views/agents/show.html.erb
<table style="margin-right:20px; width:90%; margin-top:10px" class="table table-hover table-striped" border="2">
  <thead>
    <th style="text-align:center; width:150px"><strong>الخاصية</strong</th>
    <th style="text-align:center; width:500px"><strong>البيان</strong></th>
    <th style="text-align:center; width:160px"><strong>الخاصية</strong</th>
    <th style="text-align:center; width:auto"><strong>البيان</strong></th>
  </thead>
  <tr>
    <td>
  <strong>اسم النشاط :</strong>
    </td>
    <td><strong>
     <%= @agent.name %>
      </strong>
    </td>
    <td>
  <strong>المنطقة:</strong>
    </td>
    <td>
  <%= @agent.region %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>الخريطة:</strong>
    </td>
    <td  data-no-turbolink >
      <% unless (@agent.latitude.blank? or @agent.langitude.blank?) %>
            <% if current_user.try(:admin?)  %>
                      <%= link_to "الخريطة و المسار", mapandroute_agent_path(@agent), :class => "btn btn-success", :style => "width:100%;" %>
            <% elsif @agent.ok %>
                      <%= link_to "الخريطة و المسار", mapandroute_agent_path(@agent), :class => "btn btn-success", :style => "width:100%;" %>
                 
            <% end %>
            
      <% else %>
               <strong>هذا النشاط لم يتم تسجيب احداثياتة حتى اﻵن.</strong>

      <% end %>
    </td>
     <% if current_user.try(:admin?)  %>
                  <td><b>احداثيات الموقع :</b></td>
                  <td><b>Latitude</b> :<code style="font-size:16px; color:red;"> <%= @agent.latitude %></code> / <b>Langitude</b> : <code style="font-size:16px; color:red;"><%= @agent.langitude %></code></td>
      <% else %>
                  <td><b>احداثيات الموقع :</b></td>
                  <td><b>يتم رصدها أو مراجعتها فعلياً من قبل إدارة الموقع</b></td>
      <% end %>
    
    </tr>
  <tr>
    <td>
  <strong>المجاورة:</strong>
    </td>
    <td>
  <%= @agent.neighbour %>
    </td>
  
    <td>
  <strong>الشارع:</strong>
    </td>
    <td>
  <%= @agent.street %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>العنوان:</strong>
    </td>
    <td>
  <%= @agent.address %>
    </td>
  
    <td>
  <strong>النشاط:</strong>
    </td>
    <td>
  <%= @agent.activity %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>مختصر عن النشاط:</strong>
    </td>
    <td colspan="3">
  <%= @agent.brief_of_activity %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>أيام العطلة:</strong>
    </td>
    <td>
  <%= (@agent.day_off).drop(1) %>
    </td>
  
    <td>
  <strong>العمل 24 ساعة؟:</strong>
    </td>
    <td>
  <% if @agent.twenty_four %>
    <strong>نعم</strong>
  <% else %>
    <strong>لا</strong>
  <% end %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>كلمة البحث اﻷولى:</strong>
    </td>
    <td>
  <%= @agent.word1 %>
    </td>
  
    <td>
  <strong>تليفون:</strong>
    </td>
    <td>
  <%= @agent.tel1 %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>كلمة البحث الثانية:</strong>
    </td>
    <td>
  <%= @agent.word2 %>
    </td>
  
    <td>
  <strong>تليفون:</strong>
    </td>
    <td>
  <%= @agent.tel2 %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>كلمة البحث الثالثة:</strong>
    </td>
    <td>
  <%= @agent.word3 %>
    </td>
  
    <td>
  <strong>تليفون:</strong>
    </td>
    <td>
  <%= @agent.tel3 %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>كلمة البحث الرابعة:</strong>
    </td>
    <td>
  <%= @agent.word4 %>
    </td>
  
    <td>
  <strong>بريد الكتروني:</strong>
    </td>
    <td>
  <%= @agent.email %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>كلمة البحث الخامسة:</strong>
    </td>
    <td>
  <%= @agent.word5 %>
    </td>
  
    <td>
  <strong>بداية العمل:</strong>
    </td>
    <td>
  <%= (@agent.start).strftime("%I:%M %P") %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>موقع نت:</strong>
    </td>
    <td>
    <%= @agent.website1 %>
    </td>
  
    <td>
  <strong>نهاية العمل:</strong>
    </td>
    <td>
  <%= (@agent.end).strftime("%I:%M %P") %>
    </td>
  </tr>
  <tr>
    <td>
  <strong>موقع نت:</strong>
    </td>
    <td>
  <%= @agent.website2 %>
    </td>
  
    <td>
  <strong>تم التحقق من قبل الموقع:</strong>
    </td>
    <td>
  <% if @agent.can_announce %>
    <!-- <strong>نعم</strong> -->
  <% else %>
    <!-- <strong>لا</strong> -->
  <% end %>
    </td>
  </tr>
</table>
<% if current_user %>
    <% if current_user.try(:admin?)  %>
                 <%= link_to 'تعديل', edit_agent_path(@agent), :class => "btn btn-info", :style => "margin-right:20px" %> 
                <%= link_to 'عرض الكل', agents_path, :class => "btn btn-primary" %>
        <% elsif (@agent.email==current_user.email) %>
                <%= link_to 'تعديل', edit_agent_path(@agent), :class => "btn btn-info", :style => "margin-right:20px" %> 
                
    <% end %>
<% end %>
<%= link_to 'عودة', url_for(:back), :class => "btn btn-primary" %>

app/views/agents/waited.html.erb
<h1>Listing Agents</h1>

<table class="table table-hover table-striped" border="2">
  <thead>
    <tr>
      <th>الاسم</th>
      <th>الحي أو المنطقة</th>
      <th>المجاورة</th>
      <th>الشارع</th>
      <th>العنوان</th>
      <th>النشاط</th>
      <th>مختصر عن النشاط</th>
      <th>أيام العطلة</th>
      <th>24 ساعة</th>
      <th>كلمة بحث</th>
      <th>كلمة بحث</th>
      <th>كلمة بحث</th>
      <th>كلمة بحث</th>
      <th>كلمة بحث</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th>تليفون</th>
      <th>بريد الكتروني</th>
      <th>بداية العمل</th>
      <th>نهاية العمل</th>
      <th>موقع نت</th>
      <th>موقع نت</th>
      <th>الإعلان</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= link_to truncate(agent.name, :length => 20), agent %></td>
        <td><%= truncate(agent.region, :length => 20) %></td>
        <td><%= truncate(agent.neighbour, :length => 20) %></td>
        <td><%= truncate(agent.street, :length => 20) %></td>
        <td title='<%= agent.address %>'><%= truncate(agent.address, :length => 20)  %></td>
        <td><%= truncate(agent.activity, :length => 20) %></td>
        <td title='<%= agent.brief_of_activity %>' ><%= truncate(agent.brief_of_activity, :length => 20) %></td>
        <td><%= agent.day_off.drop(1) %></td>
        <td>
          <% if agent.twenty_four %>
          <strong>نعم</strong>
          <% else %>
          <strong>لا</strong>
          <% end %>
        </td>
        <td><%= truncate(agent.word1, :length => 10) %></td>
        <td><%= truncate(agent.word2, :length => 10) %></td>
        <td><%= truncate(agent.word3, :length => 10) %></td>
        <td><%= truncate(agent.word4, :length => 10) %></td>
        <td><%= truncate(agent.word5, :length => 10) %></td>
        <td><%= truncate(agent.tel1, :length => 15) %></td>
        <td><%= truncate(agent.tel2, :length => 15) %></td>
        <td><%= truncate(agent.tel3, :length => 15) %></td>
        <td title='<%= agent.email %>'><%= truncate(agent.email, :length => 20) %></td>
        <td><%= (agent.start).strftime("%I:%M %P") %></td>
        <td><%= (agent.end).strftime("%I:%M %P") %></td>
        <td title='<%= agent.website1 %>'><%= truncate(agent.website1, :length => 20) %></td>
        <td title='<%= agent.website2 %>'><%= truncate(agent.website2, :length => 20) %></td>
        <td>
          <% if agent.can_announce %>
          <strong>نعم</strong>
          <% else %>
          <strong>لا</strong>
          <% end %>
        </td>
        
        <td><%= link_to 'تعديل', edit_agent_path(agent), :class => "btn btn-primary" %></td>
        <td>
              <% if agent.ok  %>
            <%= link_to 'تعليق', toggle_agent_path(agent), :class => "btn btn-info" %>
            <% else %>
            <%= link_to 'اقرار', toggle_agent_path(agent), :class => "btn btn-success" %>
            <% end %>
        </td>
            
        <td><%= link_to 'حذف', agent,:class => "btn btn-danger", method: :delete, data: { confirm: 'هل أنت متأكد من رغبتك في الحذف?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agent', new_agent_path, :class => "btn btn-success" %>