config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create' , via: :get
  match 'auth/failure', to: redirect('/'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get
  get 'find/search'
  get 'find/show'
  get 'find/detail'
  get 'find/advanced'
  get 'find/corrupt'
  get 'find/ads'
  get 'find/nearest'
  get 'find/nearestresult'
  get 'agents/waited'

  devise_for :users #, :controllers => {:registerations=> "registerations"}
  resources :agents do
       member do
         get 'toggle'
         get 'mapandroute'
         
    end
  end

  resources :activities

  resources :neighbours

  resources :regions
  get 'domiat/cleanall'
  get 'domiat/art'
  get 'domiat/users'
  get 'domiat/user/:id' => 'domiat#user'

  get 'domiat/clean'
  get 'domiat/exception'
  get 'domiat/show/:id'  => 'domiat#show'
  get 'domiat/welcome'
  match 'about' => 'domiat#about', :as => 'about', via: :get
  root 'domiat#welcome'
  resources :posts
  get 'suggest' => 'posts#suggest'
  get 'wantdelete' => 'posts#wantdelete'
  get 'newactivity' => 'posts#newactivity'
  get 'wrongdata' => 'posts#wrongdata'
  get 'complain' => 'posts#complain'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="rtl">
<head>
 <%= javascript_include_tag "//maps.googleapis.com/maps/api/js?language=ar" %>

  <title>New Domiat - الموقع تحت الانشاء </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link rel="shortcut icon" href="http://icons.iconarchive.com/icons/designbolts/seo/64/Natural-Link-icon.png">

  <%= csrf_meta_tags %>
  
</head>
<body class="<%= controller_name %> <%= action_name %>">
<div class="wrapper">
<nav class="navbar navbar-default navbar-inverse" role="navigation">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" data-no-turbolink>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/">www.new-domiat.com</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><a href="<%= about_path %>">اتصل بنا</a></li>
        <li class="active"><a href="<%= find_detail_path %>">بحث متقدم</a></li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">عروض <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <!--
            <li><a href="#">جامعات و مدارس</a></li>
            <li><a href="#">خدمات حكومية</a></li>
            <li class="divider"></li>-->
            <li><a href="#">شقة للإيجار</a></li>
            <li class="divider"></li>
            <li><a href="#">عقار للبيع</a></li>
            <li class="divider"></li>
            <li><a href="#">فرصة عمل</a></li>
          </ul>
        </li>
        
      </ul>
      
 <%= form_tag find_search_path, :class => "navbar-form navbar-left", method:"get", remote: true, :id => "form_search" do %>
      <div class="form-group">
      <%= text_field_tag :search, '',size:30, :class => "form-control", :placeholder =>"اكتب كلمة البحث هنا" , :autocomplete => :off %>
      </div>

      <%= submit_tag 'بحث', :class => "btn brn-default" , :id => 'search_key', :style => 'visibility:hidden' %>

      <% end %>

      <ul class="nav navbar-nav navbar-right"  data-no-turbolink >
        
      <% if current_facer %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_facer.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          
            <li><a href="#">جامعات و مدارس</a></li>
            <li><a href="#">خدمات حكومية</a></li>
            <li class="divider"></li>
            <li><%= link_to "إدراج نشاط", new_agent_path %></li>
            <li class="divider"></li>
            <% if (current_facer.admin?) %>
            <li style="display:none"><strong> <%= link_to "الانتظار", agents_waited_path %></strong></li>
            <% end %>
            <li><a href="#">عقار للبيع</a></li>
            <li class="divider"></li>
            <li><%= link_to "خروج",signout_path,id: "sign_out" %></li>
          </ul>
        </li>
        <li>

          <%= image_tag(current_facer.image, height: '50', width: '50', :style => "margin-right:-41px", :class =>"hide_in_tablet hide_in_phone") %></li>

				<% else %>
				<li><%= link_to "سجّل مع فيس بوك", "/auth/facebook", id: "sign_in" %></li>
        <li>

          <%= image_tag('facebook.png', height: '50', width: '50', :style => "margin-right:-41px", :class =>"hide_in_tablet hide_in_phone") %></li>
				<% end %>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div id="the_top_of_the_page" style="height:0; padding:0; margin:-10px"></div>   

				<% flash.each do |key, msg| %>
				<%= content_tag :p, msg, :id => key %>
				<% end %>
    <!-- <div id="result"></div> -->

<!-- Facebook script for login and api graph post -->

				<%= yield %>

            <hr>
    </div>
    <div class='push'></div>
    <footer  data-no-turbolink >
      <%= link_to "الصفحة الرئيسية", root_path %>|<%= link_to "بحث عن أقرب نشاط معين", find_detail_path %>|<%= link_to "فرصة عمل", "#" %>|<%= link_to "شقة للإيجار", "#" %>|<%= link_to "عقار للبيع", "#" %>|<%= link_to "اقتراحات", suggest_path %>|<%= link_to "إشعار بنشاط جديد أو غير مدرج", newactivity_path %>|<%= link_to "طلب حذف نشاط", wantdelete_path %>|<%= link_to "إبلاغ عن بيانات غير صحيحة", wrongdata_path %>|<%= link_to "إبلاغ عن مشكلة", complain_path %>|<%= link_to "اتصل بنا", about_path %>

      <div>© Mamdouh Abbas Farh 2015  <div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div> </div>            

    </footer>
          
</body>
</html>